---
- name: Generate password regex for user {{ user }}
  set_fact:
    regexp: ^PASSWORD {{ user }} = ([^\s]+?)$

- name: Extract password for user {{ user }}
  copy:
    dest: "{{ password_tmp_folder.path }}/{{ user }}.txt"
    content: "{{ (elastic_passwords.stdout | regex_search(regexp, '\\1', multiline=True) or []) | first }}"

- name: Store password of {{ user }} on ansible control node
  fetch:
    dest: "{{ elk_elastic_passwords_dir }}/{{ user }}.txt"
    src: "{{ password_tmp_folder.path }}/{{ user }}.txt"
    flat: true
