---
- name: Setup elasticsearch passwords
  command:
    chdir: "{{ elk_docker_compose_project_dir }}"
    cmd: docker-compose exec -T elasticsearch bin/elasticsearch-setup-passwords auto --batch
  register: elastic_passwords
  until: elastic_passwords.rc == 0
  retries: 30
  delay: 10

- name: Create tmpdir for password files
  tempfile:
    state: directory
  register: password_tmp_folder

- name: Extract elastic password
  include_tasks: elastic_extract_password.yml
  loop:
    - apm_system
    - kibana_system
    - kibana
    - logstash_system
    - beats_system
    - remote_monitoring_user
    - elastic
  loop_control:
    loop_var: user

- name: Delete password tmpdir
  file:
    state: absent
    path: "{{ password_tmp_folder.path }}"
