---
- name: Ensure the local data directory for elastic exists
  file:
    path: "{{ elk_local_data_dir }}"
    state: directory

- include_tasks: encryption_ca.yml

- name: Generate elastic logstash server certificate
  include_tasks: encryption_cert.yml
  vars:
    cert_name: "{{ elk_logstash_host | mandatory }}"

- name: Create beat client cert
  include_tasks: encryption_cert.yml
  vars:
    cert_name: "beat"
